#!/usr/bin/env bash
# Syncs curated DJ music from NAS to Music_Studio SSD
# Add/remove folders from the FOLDERS array to manage what gets copied

SRC="/Volumes/homelab/media/Music"
DEST="/Volumes/Music_Studio/DJ Music"
LOG="/tmp/dj-music-sync.log"

if [ ! -d "$SRC" ]; then
  echo "$(date): NAS not mounted at $SRC — skipping" >> "$LOG"
  exit 0
fi

if [ ! -d "$DEST" ]; then
  mkdir -p "$DEST"
fi

FOLDERS=(
  # --- Hip-Hop / Rap ---
  "A\$AP Rocky - Don't Be Dumb (FLAC)   16Bit 44.1kHz Rap  Hip-Hop  (2026)  Beats⭐"
  "A\$AP Rocky"
  "Atmosphere"
  "BigXthaPlug"
  "B.O.B Feat. Bruno Mars"
  "Common"
  "Common & Pete Rock"
  "Common feat. Brittany Howard"
  "Common feat. De La Soul"
  "Common feat. Elijah Blake"
  "Common feat. John Legend"
  "Common feat. Lily Allen"
  "Common feat. PJ"
  "Common feat. PJ & Stevie Wonder"
  "Common feat. Snoh Aalegra & Dreezy"
  "Common feat. Syd & Elena"
  "Common Sense"
  "Danny Brown"
  "De La Soul"
  "Deltron 3030"
  "Denzel Curry"
  "DJ Khaled"
  "DJ Quik"
  "DMX"
  "Dr.Alban - Collection ( 1990-2023)"
  "Eminem"
  "Eminem - Discography 1996-2020 [FLAC] vtwin88cube"
  "Flatbush ZOMBiES"
  "Flying Lotus"
  "Freddie Gibbs"
  "Future"
  "GZA+Genius"
  "Heavy Crownz - Trench Baby Turned Farmer Rap  Hip-Hop  (2026) 320_kbps Beats⭐"
  "Hoodrich Keem - Slurred Words  Rap  Hip-Hop  (2026) 320_kbps Beats⭐"
  "Immortal Technique - The 3rd World"
  "J Dilla (2006) HHIR - Donuts [The Samples]"
  "J. Cole"
  "Jeru the Damaja"
  "Joey Bada\$\$ - 1999"
  "Kanye West - Bully (First Pressing CD Edition) Rap  Hip-Hop  (2026) 320_kbps Beats⭐"
  "Kanser - It Wrote Itself"
  "Kanser - Self Titled"
  "Kanser-Future_Retro_Legacy-2008-FTD"
  "Kendrick Lamar"
  "Kendrick Lamar - Mr. Morale & The Big Steppers (2022) [24Bit-48kHz] FLAC [PMEDIA] ⭐️"
  "Kid Cudi"
  "Kris Kross"
  "Lil Dicky"
  "Lil Nas X"
  "Lil Wayne"
  "Lil Wayne, Wiz Khalifa & Imagine Dragons Feat. Logic, Ty Dolla \$ign & X Ambassadors"
  "Lil' Wayne"
  "Logic"
  "Mac Lethal"
  "Mac Miller"
  "MAC MILLER - DISCOGRAPHY [CHANNEL NEO]"
  "Method Man"
  "mgk"
  "More_Than_Lights_(Kanser)-The_Electric_Prescription_For_All_Your_Funky_Illz-2009-FTD"
  "NxWorries"
  "Onyx"
  "OutKast"
  "Post Malone"
  "Snoop Dogg"
  "Statik Selektah"
  "The Commission Feat. Jay-Z & The Notorious B.I.G"
  "The Doppelgangaz"
  "The Notorious B.I.G. Feat. Bone Thugs-N-Harmony & Twista"
  "The Notorious B.I.G. Feat. T.I"
  "The Roots"
  "Travis Scott"
  "Tyler, The Creator"
  "Veeze"
  "50 Cent - Best Of 50 Cent (2017) [FLAC] 88"
  "VA - I Believe This to Be The Supreme Formula  Hip-Hop  Poetry (2026) 320_kbps Beats⭐"

  # --- Electronic / EDM / Dance ---
  "Alesso"
  "Boards of Canada"
  "Bob Sinclar"
  "Daft Punk"
  "David Guetta"
  "Disclosure Feat. AlunaGeorge"
  "Duke Dumont"
  "Edward Maya"
  "Eric Prydz"
  "FKJ"
  "Flying Lotus"
  "Ghostland Observatory"
  "Glass Animals"
  "GoGo Penguin"
  "Gramatik"
  "Hedegaard & Martin Jensen Feat. Victoria Nadine"
  "Klangkarussell Feat. Will Heard"
  "Kygo"
  "Martin Garrix"
  "Massive Attack"
  "Nightmares on Wax"
  "Nymano j’san"
  "Pastel Ghost"
  "Philanthrope"
  "SEXY-SYNTHESIZER"
  "Stan Forebee"
  "Subtronics"
  "SwuM Benno"
  "The Flight"
  "The xx"
  "Trivecta"
  "Two Friends"
  "Zedd"

  # --- Pop / R&B / Soul ---
  "4 Non Blondes Discography"
  "6LACK"
  "ABBA"
  "Amy Winehouse - The Collection 5cd Boxset 2020 "
  "Ariana Grande"
  "Beck"
  "Bella Kay"
  "Black Eyed Peas"
  "boygenius"
  "Britney Spears"
  "Candi Staton"
  "Charlie Puth - Whatever's Clever! (2026 Pop Rock) [Flac 24-48]"
  "Coldplay"
  "Donny Hathaway"
  "Ed Sheeran"
  "Frank Ocean"
  "Gloria Gaynor"
  "Grouplove"
  "India.Arie"
  "India.Arie-Acoustic_Soul-(Special_Edition)-2CD-2007-SAW"
  "Jorja Smith"
  "Kelly Clarkson"
  "Kylie Minogue"
  "Masego"
  "Maroon 5"
  "Miley Cyrus"
  "Rihanna – ANTI (Deluxe) R&BSoul 2016 320_kbps Beats⭐"
  "Sia"
  "Smile High Teddy Roxpin"
  "The Kid LAROI - Before I Forget (2026 Pop) [Flac 24-48]"
  "Tom Odell"
  "Whitney Houston - Love, Whitney - [FLAC]-[TFM]"
  "WILLOW"
  "Yeah Yeah Yeahs"
  "Ye"

  # --- Funk / Soul / Classics ---
  "Ambassadors Of Funk featuring M. C. Mario"
  "Bionic Boogie"
  "Chuck Berry"
  "Clarence -Frogman- Henry"
  "Fats Domino"
  "Five Keys"
  "Frankie Ford"
  "Fun Lovin' Criminals - Come Find Yourself (1996)"
  "Jerry Lee Lewis"
  "Johnny Cash"
  "Johnny Cash - American Recordings (1994 Country) [Flac 16-44]"
  "Little Richard"
  "Marvin Gaye"
  "Sly Johnson - Mister Johnson (2026 Soul Funk RnB) [Flac 24-44]"
  "Vulfpeck"

  # --- Rock / Alternative ---
  "Aerosmith"
  "Alice Cooper"
  "Billy Idol"
  "Blood Sugar Sex Magik"
  "Bon Jovi"
  "Caesars"
  "Counting Crows"
  "Def Leppard"
  "Disturbed"
  "Fleetwood Mac - Fleetwood Mac 1975 to 1987 (2025) [16Bit-44.1kHz] FLAC [PMEDIA] ⭐️"
  "Foreigner"
  "Frank Zappa"
  "Franz Ferdinand"
  "Godsmack"
  "Green Day"
  "Grizzly Bear"
  "Gus G"
  "Hardline"
  "Led Zeppelin - Studio Discography 1969 - 1982 [FLAC] - Kitlope"
  "Metallica"
  "Mr. Big"
  "Pink Floyd"
  "Poison"
  "Rage Against The Machine - The Collection (2010) [FLAC] 88"
  "Rammstein"
  "Red Hot Chili Peppers"
  "Red Hot Chili Peppers - Californication (1999) (PBTHAL LP 24-96) [FLAC] vtwin88cube"
  "Red Hot Chili Peppers - Greatest Hits (Remastered)"
  "REO Speedwagon"
  "Sonic Youth"
  "Steve Miller Band"
  "Sublime"
  "Suicidal Tendencies - Suicidal For Life (1994)"
  "Talking Heads"
  "The Beach Boys"
  "The Beatles"
  "The Black Keys"
  "The Black Keys - Dropout Boogie (2022) FLAC [PMEDIA] ⭐️"
  "The Cure"
  "The Darkness"
  "The Hives"
  "The Kinks"
  "The Offspring"
  "The Rolling Stones - The Marquee Club (Live In 1971)  2015 EU LP"
  "The Smashing Pumpkins"
  "The Yardbirds"
  "Tool"
  "U2"
  "Wolfmother"
  "Yes"
)

echo "$(date): Starting DJ music sync" >> "$LOG"
synced=0
skipped=0

for folder in "${FOLDERS[@]}"; do
  src_path="$SRC/$folder"
  if [ -d "$src_path" ]; then
    rsync -a --ignore-existing "$src_path" "$DEST/" >> "$LOG" 2>&1
    echo "  synced: $folder" >> "$LOG"
    ((synced++))
  else
    ((skipped++))
  fi
done

echo "$(date): Done — $synced synced, $skipped not found on NAS" >> "$LOG"
